name: Run tests and deploy to github pages
on:
  push:
    paths:
    - '**.js'
    - '**.ts'
    - '**.scss'
    - '**.vue'
    branches:
      - dev
jobs:
  run-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Clean install dependencies
        run: npm ci
      - name: Run unit tests
        run: |
          npm run test:unit
